# Generated by Django 4.1.4 on 2022-12-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wilaya', models.CharField(max_length=200)),
                ('Commune', models.CharField(max_length=200)),
                ('adresseIMB', models.CharField(max_length=1000)),
                ('adresseURL', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcatégorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='théme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('théme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreAnn', models.CharField(max_length=50)),
                ('modalité', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=500)),
                ('tarif', models.CharField(max_length=200)),
                ('photos', models.CharField(max_length=300)),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Findin.catégorie')),
                ('lieudeFormation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Findin.adresse')),
                ('théme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Findin.théme')),
            ],
        ),
    ]
